// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PubHealth.Data;

#nullable disable

namespace PubHealth.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426011108_transitions")]
    partial class transitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PubHealth.Models.Slide", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFork")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlideImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlideText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Slides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Test",
                            IsFork = false,
                            QuestionText = "Hello?",
                            SlideImageUrl = "testurl.com",
                            SlideText = "TestSlide"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Test",
                            IsFork = false,
                            QuestionText = "Hello?",
                            SlideImageUrl = "testurl.com",
                            SlideText = "TestSlide2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Test",
                            IsFork = false,
                            QuestionText = "Why?",
                            SlideImageUrl = "testurl.com",
                            SlideText = "TestSlide3"
                        });
                });

            modelBuilder.Entity("PubHealth.Models.Transition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AnswerText1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerText2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChildSlideId")
                        .HasColumnType("int");

                    b.Property<int>("ParentSlideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText1 = "Answer1",
                            AnswerText2 = "Answer2",
                            ChildSlideId = 2,
                            ParentSlideId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerText1 = "Answer3",
                            AnswerText2 = "Answer4",
                            ChildSlideId = 3,
                            ParentSlideId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
